### ISSUE TITLE
Move to using ES6

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/open2017#15]
@QuincyLarson, @raisedadead, what do you think of this? We could use some simple npm scripts (no need for `webpack.config.js`).

I'm happy to refactor the current JS if this is decided 👍

**Comment by raisedadead** [comment]
Sounds, good. 

But considering this to be a dead simple landing page, may throw off contributors with the tooling involved?

**Comment by atjonathan** [comment]
@raisedadead, all they would need to do is install webpack globally, using `npm install webpack --global` and then run `npm run dev`. I can make an in-depth contributing guide. I just think it's better if we use and encourage the newest iteration of JavaScript.

**Comment by ErikUu** [comment]
Think it sounds good.

**Comment by atjonathan** [comment]
@QuincyLarson, do I have the go ahead?
Also: I'm gonna try and minimize/remove the need for jQuery so the site loads a lot faster.

**Comment by QuincyLarson** [comment]
@atjonathan I agree that we should keep this simple and easy to contribute to. There's nothing wrong with jQuery. It's already cached in almost every browser on the planet.
