### ISSUE TITLE
Fixed side-nav

### ISSUE THREAD

**Issue by ErikUu** [FreeCodeCamp/open2017#17]
What do you guys think about making the _side-nav_ stick (fixed) when scrolling down?

**Comment by realslimshanky** [comment]
That would be cool. I can work on this issue.

**Comment by ErikUu** [comment]
Go for it!

**Comment by QuincyLarson** [comment]
@realslimshanky @ErikUu yes - I agree that this would be better. Which of you wants to tackle this? Be sure to do a fresh branch off of master.

**Comment by ErikUu** [comment]
I can do it, or did you want to tackle it @realslimshanky?

**Comment by sjclayton** [comment]
@QuincyLarson this can be closed - fixed by PR #23
