### ISSUE TITLE
Site not scaling correctly on mobile

### ISSUE THREAD

**Issue by ErikUu** [FreeCodeCamp/open2017#28]
The website does not scale correctly on IOS.

<img src="https://cloud.githubusercontent.com/assets/8659002/21472174/d3639126-cacc-11e6-98a1-1a5172fafa53.png" width="400">

**Comment by sjclayton** [comment]
@ErikUu - Hmmm, that is odd... not sure what is causing that, it seems to scale just fine on Android, but apparently not on iOS... *shrugs*

**Comment by sjclayton** [comment]
Still haven't figured this one out...

**Comment by realslimshanky** [comment]
This might help http://stackoverflow.com/questions/8154505/how-can-i-force-a-site-to-scale-to-fix-for-mobile-iphone-android

**Comment by sjclayton** [comment]
@realslimshanky pull request with proposed fix is up for review --> #31 -- @ErikUu needs testing, as I have no way of directly testing it myself as I do not own an iOS device and all the online mobile device testing sites said that everything was fine (passed with 97-98% mobile friendly design) before even making any changes in the first place.

**Comment by realslimshanky** [comment]
I tested it on iPhone 6, works perfectly :+1:
