### ISSUE TITLE
Text not wrapping in guest list

### ISSUE THREAD

**Issue by sjclayton** [freeCodeCamp/open2017#34]
The bio text description for Sarah Drasner does not appear to wrap properly compared to all the other guest entries.

I have looked at this a little myself and cannot figure it out... it just sticks out rather sorely compared to the rest of the list.

**Comment by sjclayton** [comment]
@QuincyLarson ^^

**Comment by QuincyLarson** [comment]
@sjclayton good catch. Yes - it sounds like we need to insert a break somehow for long text. We may use this same webpage again next year, and it would be nice if we could fix this, so if you're interested in fixing it I can merge the PR :)

**Comment by 123bless** [comment]
How do i get invited
